# Generated by Django 6.0 on 2025-12-30 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción del Perfil')),
                ('perfilactivo', models.BooleanField(default=True, verbose_name='¿Perfil Activo?')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cv_pdf/', verbose_name='Archivo PDF (Descargable)')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/', verbose_name='Foto de Perfil')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad')),
                ('lugarnacimiento', models.CharField(max_length=60, verbose_name='Lugar de Nacimiento')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('numerocedula', models.CharField(max_length=10, unique=True, verbose_name='Número de Cédula')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo')),
                ('estadocivil', models.CharField(max_length=50, verbose_name='Estado Civil')),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True, verbose_name='Licencia de Conducir')),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Convencional')),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección Trabajo')),
                ('direcciondomiciliaria', models.CharField(max_length=50, verbose_name='Dirección Domiciliaria')),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name': 'Dato Personal',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('fechainicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fechafin', models.DateField(verbose_name='Fecha Fin')),
                ('totalhoras', models.IntegerField(verbose_name='Total Horas')),
                ('descripcioncurso', models.CharField(max_length=100, verbose_name='Descripción')),
                ('entidadpatrocinadora', models.CharField(max_length=100, verbose_name='Entidad')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Visible en Web')),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/cursos/', verbose_name='Certificado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name': 'Curso Realizado',
                'verbose_name_plural': 'Cursos Realizados',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100, verbose_name='Cargo Desempeñado')),
                ('nombrempresa', models.CharField(max_length=50, verbose_name='Nombre de la Empresa')),
                ('lugarempresa', models.CharField(max_length=50, verbose_name='Lugar de la Empresa')),
                ('fechainiciogestion', models.DateField(verbose_name='Fecha Inicio')),
                ('fechafingestion', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('descripcionfunciones', models.CharField(max_length=100, verbose_name='Funciones')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Visible en Web')),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/laboral/', verbose_name='Certificado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
            },
        ),
        migrations.CreateModel(
            name='HabilidadTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilidad', models.CharField(max_length=50, verbose_name='Tecnología (ej. Python)')),
                ('porcentaje', models.IntegerField(help_text='Solo números, sin el signo %', verbose_name='Porcentaje (0-100)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name': 'Habilidad Técnica',
                'verbose_name_plural': 'Habilidades Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100, verbose_name='Tipo')),
                ('fechareconocimiento', models.DateField(verbose_name='Fecha')),
                ('descripcionreconocimiento', models.CharField(max_length=100, verbose_name='Descripción')),
                ('entidadpatrocinadora', models.CharField(max_length=100, verbose_name='Entidad')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Visible en Web')),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', verbose_name='Certificado o Evidencia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Visible en Web')),
                ('imagenproducto', models.ImageField(blank=True, null=True, upload_to='ventas_garage/', verbose_name='Foto del Producto')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name': 'Venta de Garage',
                'verbose_name_plural': 'Ventas de Garage',
            },
        ),
    ]
