# Generated by Django 6.0 on 2025-12-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesión / Título')),
                ('perfil', models.TextField(help_text='Resumen de tus habilidades y objetivos', verbose_name='Perfil Profesional')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Hoja de Vida',
                'verbose_name_plural': 'Hojas de Vida',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo Ocupado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('trabajo_actual', models.BooleanField(default=False, verbose_name='¿Es el trabajo actual?')),
                ('descripcion', models.TextField(verbose_name='Descripción de responsabilidades')),
                ('hoja_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='tasks.hojadevida')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
            },
        ),
    ]
