# Generated by Django 6.0 on 2025-12-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_datospersonales_cursosrealizados_experiencialaboral_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'verbose_name': 'Curso Realizado', 'verbose_name_plural': 'Cursos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencias Laborales'},
        ),
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'verbose_name': 'Producto Académico', 'verbose_name_plural': 'Productos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'verbose_name': 'Producto Laboral', 'verbose_name_plural': 'Productos Laborales'},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'verbose_name': 'Reconocimiento', 'verbose_name_plural': 'Reconocimientos'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'verbose_name': 'Venta de Garage', 'verbose_name_plural': 'Ventas de Garage'},
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en Web'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email Entidad'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='entidadpatrocinadora',
            field=models.CharField(max_length=100, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecurso',
            field=models.CharField(max_length=100, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(verbose_name='Total Horas'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción del Perfil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=50, verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección Trabajo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Licencia de Conducir'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(max_length=60, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(max_length=20, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=60, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de Cédula'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.BooleanField(default=True, verbose_name='¿Perfil Activo?'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Convencional'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en Web'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=100, verbose_name='Cargo Desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(max_length=100, verbose_name='Funciones'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email de la Empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(max_length=50, verbose_name='Lugar de la Empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/laboral/', verbose_name='Certificado (PDF/Img)'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Web de la Empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en Web'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(max_length=100, verbose_name='Clasificador'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='nombrerecurso',
            field=models.CharField(max_length=100, verbose_name='Nombre Recurso'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en Web'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='nombreproducto',
            field=models.CharField(max_length=100, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en Web'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(max_length=100, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Visible en Web'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=100, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio'),
        ),
    ]
