# Generated by Django 6.0 on 2025-12-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_cursosrealizados_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoslaborales',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
        ),
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='idcursorealizado',
        ),
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='emailempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='idexperiencilaboral',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='idreconocimiento',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='idventagarage',
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cv_pdf/', verbose_name='Archivo PDF (Descargable)'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/laboral/', verbose_name='Certificado'),
        ),
        migrations.DeleteModel(
            name='ProductosAcademicos',
        ),
        migrations.DeleteModel(
            name='ProductosLaborales',
        ),
    ]
