# Generated by Django 6.0 on 2025-12-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_productoslaborales_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
