# Generated by Django 6.0 on 2025-12-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_datospersonales_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', verbose_name='Certificado o Evidencia'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagenproducto',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_garage/', verbose_name='Foto del Producto'),
        ),
    ]
