# Generated by Django 6.0 on 2025-12-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_reconocimientos_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
