# Generated by Django 6.0 on 2025-12-30 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_datospersonales_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilidad', models.CharField(max_length=50, verbose_name='Tecnología (ej. Python)')),
                ('porcentaje', models.IntegerField(help_text='Solo números, sin el signo %', verbose_name='Porcentaje (0-100)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name': 'Habilidad Técnica',
                'verbose_name_plural': 'Habilidades Técnicas',
            },
        ),
    ]
